/*  BestNotePad.java  */
/**
 * @Mukesh Shah : (M) + 91 99 79 98 73 26
 * @ Email : mukesh1710@yahoo.co.in 
 */

import javax.swing.*;
import javax.swing.undo.*;
import java.io.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.event.*;
import java.util.*;
import javax.swing.text.*;
import java.text.*;

public class BestNotePad extends javax.swing.JFrame {
    
    UndoManager undo = new UndoManager();
  //  UndoAction undoAction = new UndoAction();
    boolean opend =false;
    String wholeText,findString, filename=null;
    int ind =0;
    
    /** Creates new form BestNotePad */
    public BestNotePad() {
        initComponents();
      
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        POPUP = new javax.swing.JPopupMenu();
        CUTPOPUP = new javax.swing.JMenuItem();
        COPYPOPUP = new javax.swing.JMenuItem();
        PASTEPOPUP = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JSeparator();
        DELETEPOPUP = new javax.swing.JMenuItem();
        SELECTALLPOPUP = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        FILE = new javax.swing.JMenu();
        NEWFILE = new javax.swing.JMenuItem();
        OPENFILE = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        SAVEFILE = new javax.swing.JMenuItem();
        SAVEASFILE = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        EXITFILE = new javax.swing.JMenuItem();
        EDIT = new javax.swing.JMenu();
        UNDOEDIT = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        CUTEDIT = new javax.swing.JMenuItem();
        COPYEDIT = new javax.swing.JMenuItem();
        PASTEEDIT = new javax.swing.JMenuItem();
        DELETEEDIT = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        SELECTALLEDIT = new javax.swing.JMenuItem();
        TIMEDATEEDIT = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        WORDWRAPEDIT = new javax.swing.JMenuItem();
        SETFONEDIT = new javax.swing.JMenuItem();
        SEARCH = new javax.swing.JMenu();
        FINDSEARCH = new javax.swing.JMenuItem();
        FINDNEXTSEARCh = new javax.swing.JMenuItem();
        HELP = new javax.swing.JMenu();
        ABOUTHELp = new javax.swing.JMenuItem();

        CUTPOPUP.setText("Cut");
        POPUP.add(CUTPOPUP);

        COPYPOPUP.setText("Copy");
        POPUP.add(COPYPOPUP);

        PASTEPOPUP.setText("Paste");
        POPUP.add(PASTEPOPUP);

        POPUP.add(jSeparator6);

        DELETEPOPUP.setText("Delete");
        POPUP.add(DELETEPOPUP);

        SELECTALLPOPUP.setText("Select All");
        POPUP.add(SELECTALLPOPUP);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        text.setColumns(20);
        text.setLineWrap(true);
        text.setRows(5);
        text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                textMouseReleased(evt);
            }
        });

        jScrollPane1.setViewportView(text);

        FILE.setText("File");
        NEWFILE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        NEWFILE.setText("New");
        FILE.add(NEWFILE);

        OPENFILE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OPENFILE.setText("Open");
        FILE.add(OPENFILE);

        FILE.add(jSeparator1);

        SAVEFILE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SAVEFILE.setText("Save");
        FILE.add(SAVEFILE);

        SAVEASFILE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        SAVEASFILE.setText("Save As");
        FILE.add(SAVEASFILE);

        FILE.add(jSeparator2);

        EXITFILE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        EXITFILE.setText("Exit");
        FILE.add(EXITFILE);

        jMenuBar1.add(FILE);

        EDIT.setText("Edit");
        UNDOEDIT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        UNDOEDIT.setText("Un Do");
        EDIT.add(UNDOEDIT);

        EDIT.add(jSeparator3);

        CUTEDIT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        CUTEDIT.setText("Cut..");
        EDIT.add(CUTEDIT);

        COPYEDIT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        COPYEDIT.setText("Copy");
        EDIT.add(COPYEDIT);

        PASTEEDIT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        PASTEEDIT.setText("Paste..");
        EDIT.add(PASTEEDIT);

        DELETEEDIT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        DELETEEDIT.setText("Delete");
        EDIT.add(DELETEEDIT);

        EDIT.add(jSeparator4);

        SELECTALLEDIT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        SELECTALLEDIT.setText("Select All");
        EDIT.add(SELECTALLEDIT);

        TIMEDATEEDIT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        TIMEDATEEDIT.setText("Time & Date");
        EDIT.add(TIMEDATEEDIT);

        EDIT.add(jSeparator5);

        WORDWRAPEDIT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_MASK));
        WORDWRAPEDIT.setText("Word Wrap ");
        EDIT.add(WORDWRAPEDIT);

        SETFONEDIT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        SETFONEDIT.setText("Font");
        EDIT.add(SETFONEDIT);

        jMenuBar1.add(EDIT);

        SEARCH.setText("Search");
        FINDSEARCH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        FINDSEARCH.setText("Find");
        SEARCH.add(FINDSEARCH);

        FINDNEXTSEARCh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        FINDNEXTSEARCh.setText("Find Next");
        SEARCH.add(FINDNEXTSEARCh);

        jMenuBar1.add(SEARCH);

        HELP.setText("Help");
        ABOUTHELp.setText("About BeST NotePad");
        HELP.add(ABOUTHELp);

        jMenuBar1.add(HELP);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
// TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null,"Do You really want to Quit??");
        switch(response)
        {
            case 0 : dispose();
                    break;            
                    
            case 1 : this.setVisible(true);
        }        
        
    }//GEN-LAST:event_formWindowClosing

    private void textMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMouseReleased
// TODO add your handling code here:
        if(evt.isPopupTrigger())
        {
            POPUP.show(evt.getComponent(),evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_textMouseReleased

    private void textMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMousePressed
// TODO add your handling code here:  System.out.println("Mouse is Pressed");
        if(evt.isPopupTrigger())
        {
         
            POPUP.show(evt.getComponent(),evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_textMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BestNotePad().setVisible(true);
            }
        });
    }
    /* Class For UndoListener     */
    class UndoListener implements UndoableEditListener
    {
        
        public void undoableEditHappened(UndoableEditEvent e) {
            undo.addEdit(e.getEdit());
         //   UNDOEDIT.updateUI();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ABOUTHELp;
    private javax.swing.JMenuItem COPYEDIT;
    private javax.swing.JMenuItem COPYPOPUP;
    private javax.swing.JMenuItem CUTEDIT;
    private javax.swing.JMenuItem CUTPOPUP;
    private javax.swing.JMenuItem DELETEEDIT;
    private javax.swing.JMenuItem DELETEPOPUP;
    private javax.swing.JMenu EDIT;
    private javax.swing.JMenuItem EXITFILE;
    private javax.swing.JMenu FILE;
    private javax.swing.JMenuItem FINDNEXTSEARCh;
    private javax.swing.JMenuItem FINDSEARCH;
    private javax.swing.JMenu HELP;
    private javax.swing.JMenuItem NEWFILE;
    private javax.swing.JMenuItem OPENFILE;
    private javax.swing.JMenuItem PASTEEDIT;
    private javax.swing.JMenuItem PASTEPOPUP;
    private javax.swing.JPopupMenu POPUP;
    private javax.swing.JMenuItem SAVEASFILE;
    private javax.swing.JMenuItem SAVEFILE;
    private javax.swing.JMenu SEARCH;
    private javax.swing.JMenuItem SELECTALLEDIT;
    private javax.swing.JMenuItem SELECTALLPOPUP;
    private javax.swing.JMenuItem SETFONEDIT;
    private javax.swing.JMenuItem TIMEDATEEDIT;
    private javax.swing.JMenuItem UNDOEDIT;
    private javax.swing.JMenuItem WORDWRAPEDIT;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
    
}
